# Generated by Django 3.2.8 on 2025-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(blank=True, to="product.Category"),
        ),
    ]
